### PR TITLE
Listing page - item tabs section

### PR DESCRIPTION
**Pull request by s4dmw**
This feature will house the "item details", "ratings/reviews", and "shipping & policies" features on the Listing page.
- [x] html
- [x] scss/css
  - [x] format nav bar
  - [x] active tab
  - [x] stars on ratings tab
    - [ ] getting stars to "work"...wellllllll
- [x] js
  - [x] show/hide tabs

link to feature issue: https://github.com/TIY-Durham/TIY-Catalog/issues/15

### CODE REVIEW

**Comment by s4dmw** [comment]
##### screen shots

**note:** padding and black border there temporarily to highlight the area

screen shot 2015-10-14 at 9 35 53 pm

screen shot 2015-10-14 at 9 43 07 pm

screen shot 2015-10-14 at 9 43 53 pm

**Comment by s4dmw** [comment]
screen shot 2015-10-14 at 9 43 07 pm

**Comment by s4dmw** [comment]
screen shot 2015-10-14 at 9 43 53 pm

**Comment by jeremyrist** [comment]
Looks great, David! I'm trying to work out Postman/the-API to get the Ratings information

**Pull request merged**
